export default {
  products: [
    {
      _id: '1',
      name: 'COMPLETE 22 BLACKOUT 2.0',
      brand: 'PENNY',
      category: 'Skateboard',
      image: '/images/d1.jpg',
      price: 58.59,
	  size: [22, 27, 32],
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'TONY HAWK CREST 22" COMPLETE',
      brand: 'PENNY',
      category: 'Skateboard',
      image: '/images/d2.jpg',
      price: 83.72,
	  size: [22, 27, 32],
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '3',
      name: 'CLASSIC WAVE SPLICE SHARK 8.8" COMPLETE',
      brand: 'SANTA CRUZ',
      category: 'Skateboard',
      image: '/images/cruz1.jpg',
      price: 159.99,
	  size: [32],
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    }, {
      _id: '4',
      name: 'TOXIC HAND SHAPED 9.7" COMPLETE',
      brand: 'SANTA CRUZ',
      category: 'Skateboard',
      image: '/images/cruz2.jpg',
      price: 159.99,
	  size: [31],
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },{
      _id: '5',
      name: 'CLASSIC DOT 80S CRUZER 9.35" COMPLETE',
      brand: 'SANTA CRUZ',
      category: 'Skateboard',
      image: '/images/cruz3.jpg',
      price: 129.99,
	  size: [30],
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },

  ]
}
